### ISSUE TITLE
Add Support for Pandas 1.3.1

### ISSUE THREAD

**Issue by kjaymiller** [elastic/eland#371] opened 2021-08-04 17:36 UTC
I saw issue #359 however I'm running into the issue now with

```
pandas==1.3.1
eland==7.13.0b1
```

Error message is the same - `ImportError: cannot import name 'ABCIndexClass' from 'pandas.core.dtypes.generic'`

**Comment by sethmlarson** [comment] 2021-08-04 17:57
Last night's CI run [used pandas 1.3.1 and passed successfully](https://clients-ci.elastic.co/job/elastic+eland+master/789/ELASTICSEARCH_VERSION=8.0.0-SNAPSHOT,PANDAS_VERSION=1.3.0,PYTHON_VERSION=3.9,TEST_SUITE=xpack,label=linux/console). Going to close this as duplicate of https://github.com/elastic/eland/issues/359 and therefore closed in https://github.com/elastic/eland/pull/362

**Closed by sethmlarson** 2021-08-04 17:57 UTC
