### ISSUE TITLE
Support for importing model

### ISSUE THREAD

**Issue by mauiroma** [elastic/eland#687] opened 2024-04-12 16:29 UTC
Using Eland to load the model https://huggingface.co/osiria/minilm-l12-h384-italian-cased , I obtain this error
```
Establishing connection to Elasticsearch
Connected to cluster named 'xxxxxxxx' (version: 8.13.2)
Loading HuggingFace transformer tokenizer and model 'osiria/minilm-l12-h384-italian-cased'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2256, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/xlm_roberta/tokenization_xlm_roberta.py", line 154, in __init__
    self.sp_model.Load(str(vocab_file))
  File "/usr/local/lib/python3.10/site-packages/sentencepiece/__init__.py", line 961, in Load
    return self.LoadFromFile(model_file)
  File "/usr/local/lib/python3.10/site-packages/sentencepiece/__init__.py", line 316, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
OSError: Not found: "None": No such file or directory Error #2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/eland_import_hub_model", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/eland/cli/eland_import_hub_model.py", line 269, in main
    tm = TransformerModel(
  File "/usr/local/lib/python3.10/site-packages/eland/ml/pytorch/transformers.py", line 655, in __init__
    self._tokenizer = transformers.AutoTokenizer.from_pretrained(
  File "/usr/local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 768, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2024, in from_pretrained
    return cls._from_pretrained(
  File "/usr/local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2258, in _from_pretrained
    raise OSError(
OSError: Unable to load vocabulary from file. Please check that the provided vocabulary is accessible and not corrupted.
```

The command used is this:
```
eland_import_hub_model --cloud-id '$CLOUD_ID'   --es-username $USERNAME --es-password '$PASSWORD'  --es-model-id 'osirialegal'  --hub-model-id osiria/minilm-l12-h384-italian-cased
```

**Comment by federicocesarini1** [comment] 2024-04-17 14:30
@davidkyle i followed your instructions but now i get another error: torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

is there another way to make it work?

**Comment by davidkyle** [comment] 2024-05-03 09:45
Thanks for the stack trace.

When Eland is used to import the model it runs a test evaluation to measure the size of the embedding produced by the model. This is part of the config and useful when configuring the `dims` parameter of the dense vector field mapping in Elasticsearch. The error is from this test evaluation, in this case it is probably because the inputs to `forward(...)` not in the expected format.

**Comment by davidkyle** [comment] 2024-05-21 14:00
I looked into this again and there is another issue that prevents this model being used in Elasticsearch.

Elasticsearch uses the `libtorch` C++ library to run the NLP models. The models must be converted to the TorchScript format before they can run in libtorch, this conversion is one of the things the Eland script does. Tracing this particular model fails with an error: 
```
RuntimeError: Encountering a dict at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.
```

Here is a Python snippet that reproduces the failed trace operation. I used a local copy of the repository with the `sentencepiece.bpe.model` added as mention [above](https://github.com/elastic/eland/issues/687#issuecomment-2060871990)


```Python
from transformers import AutoModel, AutoTokenizer
import torch
# load model & tokenizer
tokenizer = AutoTokenizer.from_pretrained('<directory of the downloaded model to which we added sentencepiece>', use_fast=False)
model = AutoModel.from_pretrained('<directory of the downloaded model to which we added sentencepiece>')
# create sample input
encoded_input = tokenizer("Replace me by any text you'd like.", return_tensors='pt')
trace_inputs = (encoded_input["input_ids"], encoded_input["attention_mask"])
# trace model fails
traced = torch.jit.trace(model, example_inputs=trace_inputs)
```

Closing this issue as if the model cannot be traced it cannot be supported.

**Comment by serenachou** [comment] 2024-09-03 20:43
@arisonl  @davidkyle  @dimkots  - just FYI competitors like Weaviate support Jina AI models. Is there a plan to address this for us?

**Comment by davidkyle** [comment] 2024-09-04 10:16
The general problem of importing a model without a vocabulary file is tracked in #721. Closing this issue as there are other problems with this specific model (osiria/minilm-l12-h384-italian-cased) which means it cannot be imported.

**Closed by davidkyle** 2024-09-04 10:16 UTC
Labels: bug
