### ISSUE TITLE
Add options to eland_import_hub_model for specifying CA certificates

### ISSUE THREAD

**Issue by ailanmar** [elastic/eland#422] opened 2021-12-21 16:28 UTC
When uploading a Huggingface model to an ES cluster deployed through the [ML-QA framework](https://docs.elastic.dev/ml-team/docs/qa/framework) with SSL enabled (which is default) using `eland_import_hub_model ` i.e.

```
eland_import_hub_model \
--url $ELASTICSEARCH_URL \
--hub-model-id sentence-transformers/all-MiniLM-L6-v2 \
--task-type text_embedding \
--start
```

throws the following error:

```
elasticsearch.exceptions.SSLError: ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125))
```

A common way to overcome this problem is to deploy the cluster disabling SSL:

```
LOCAL_CLUSTER_NAME=nlp-demo
ES_SSL_ENABLED=false KIBANA_SSL_ENABLED=false
./gradlew deployCluster startCluster
```

Here I propose an alternative way to overcome this problem in a generic way which will make `eland_import_hub_model` work in all circumstances :
Modify Line 86: 
``` python
es = elasticsearch.Elasticsearch(args.url, timeout=300)  # 5 minute timeout
```
by
``` python
try:
    es = elasticsearch.Elasticsearch(args.url, timeout=300) # 5 minute timeout
    es.info()
except elasticsearch.SSLError:
    from elasticsearch.connection import create_ssl_context
    import ssl
    ssl_context = create_ssl_context()
    ssl_context.check_hostname = False
    ssl_context.verify_mode = ssl.CERT_NONE
    es = elasticsearch.Elasticsearch(args.url, verify_certs = False, ssl_context = ssl_context, timeout=300) # 5 minute timeout
```

In this way it would be possible to establish connection to the ES host whether SSL is enabled or not and upload the hub model. I have tested this modification and works fine. If it looks good to you I will make a PR with the changes.

**Comment by sethmlarson** [comment] 2022-03-07 20:29
Instead of disabling certificate verification we should add options to specify certificates like `--ca-certs`.

**Comment by RiccardoTOTI** [comment] 2022-03-10 16:56
i have a similar problem but it's something like that: `elastic_transport.TlsError: TLS error caused by: TlsError(TLS error caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)))`. How can i resolve it?

**Comment by sethmlarson** [comment] 2022-04-01 15:55
Closed via https://github.com/elastic/eland/pull/441 and now released.

**Closed by sethmlarson** 2022-04-01 15:55 UTC
