### ISSUE TITLE
filter by time

### ISSUE THREAD

**Issue by geoHeil** [elastic/eland#341] opened 2021-01-18 10:19 UTC
I have an eland dataframe with a timestamp column. In pandas I can easily filter it by time. How can I tell Eland to filter it? The regular method fails with an not implemented exception.

```
ts = pd._libs.tslibs.timestamps.Timestamp('2020-12-01')
df[df['@timestamp'] >= ts].head()
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-24-730a991373fa> in <module>
----> 1 df_filtered = df[df['@timestamp'] >= ts]
      2 df_filtered.head()

C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\eland\series.py in __ge__(self, other)
    489             return GreaterEqual(field=self.name, value=other)
    490         else:
--> 491             raise NotImplementedError(other, type(other))
    492 
    493     def __le__(self, other: Union[int, float, "Series"]) -> BooleanFilter:

NotImplementedError: (Timestamp('2020-12-01 00:00:00'), <class 'pandas._libs.tslibs.timestamps.Timestamp'>)
```

**Comment by geoHeil** [comment] 2021-01-18 10:49
https://github.com/elastic/eland/issues/265

**Comment by sethmlarson** [comment] 2021-01-21 18:04
Thanks for opening this, I'm going to close this as duplicate of the issue you linked to. If there's additional requirements you can add them to #265.

**Closed by sethmlarson** 2021-01-21 18:04 UTC
